export const DashboardLinks = [
    {
        label:'dashboard',
        icon:'lucide:layout-dashboard',
        link:'/',
        color:'text-sky-400',
        bgColor:'bg-sky-400/10',
    },
    {
        label:'conversation',
        icon:'lucide:message-square',
        link:'/conversation',
        color:'text-orange-400',
        bgColor:'bg-orange-400/10',
    },
    {
        label:'image',
        icon:'lucide:image',
        link:'/image',
        color:'text-red-400',
        bgColor:'bg-red-400/10',
    },
    {
        label:'music',
        icon:'lucide:music',
        link:'/music',
        color:'text-brown-400',
        bgColor:'bg-brown-400/10',
    },
    {
        label:'video',
        icon:'lucide:video',
        link:'/video',
        color:'text-brown-400',
        bgColor:'bg-brown-400/10',
    },
    {
        label:'code',
        icon:'lucide:code',
        link:'/code',
        color:'text-blue-400',
        bgColor:'bg-blue-400/10',
    },
    {
        label:'settings',
        icon:'lucide:settings',
        link:'/settings',
        color:'text-green-400',
        bgColor:'bg-green-400/10',
    }
]